"""
Comprehensive Prototype Business Dataset for Rural Entrepreneurs in India.
Contains realistic baseline estimates, costs, equipment requirements, risk levels, and assumptions.
"""

from typing import List, Dict, Any

RURAL_BUSINESSES: List[Dict[str, Any]] = [
    {
        "id": "dairy-farming",
        "name": "Dairy Farming (2-5 Cows/Buffaloes)",
        "category": "Agriculture & Livestock",
        "minimum_investment": 80000.0,
        "recommended_investment": 150000.0,
        "equipment_cost": 45000.0,
        "working_capital": 35000.0,
        "estimated_monthly_revenue": 42000.0,
        "estimated_monthly_expenses": 22000.0,
        "expected_profit": 20000.0,
        "break_even_months": 7.5,
        "risk_level": "Medium",
        "required_skills": ["Farming", "Animal Care", "Local Milk Supply Network"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "High daily local demand for fresh milk and ghee; tie-ups with local cooperatives (AMUL, Mother Dairy, state milk federations).",
        "description": "Establishment of a small-scale dairy farm with high-yielding milch cattle, automated/semi-automated milking equipment, and local milk collection route setup."
    },
    {
        "id": "poultry-farming",
        "name": "Broiler & Layer Poultry Farming",
        "category": "Agriculture & Livestock",
        "minimum_investment": 70000.0,
        "recommended_investment": 120000.0,
        "equipment_cost": 40000.0,
        "working_capital": 30000.0,
        "estimated_monthly_revenue": 38000.0,
        "estimated_monthly_expenses": 21000.0,
        "expected_profit": 17000.0,
        "break_even_months": 7.0,
        "risk_level": "Medium-High",
        "required_skills": ["Poultry Management", "Disease Control", "Feed Mixing"],
        "location_suitability": ["Rural"],
        "demand_assumptions": "Strong demand for poultry meat and eggs in local weekly markets (haats) and urban butcher shops.",
        "description": "Small batch poultry farm providing fresh eggs and broiler meat with controlled shed climate and bio-security measures."
    },
    {
        "id": "mushroom-farming",
        "name": "Oyster & Button Mushroom Cultivation",
        "category": "Agro-Processing & Cultivation",
        "minimum_investment": 35000.0,
        "recommended_investment": 65000.0,
        "equipment_cost": 20000.0,
        "working_capital": 15000.0,
        "estimated_monthly_revenue": 28000.0,
        "estimated_monthly_expenses": 11000.0,
        "expected_profit": 17000.0,
        "break_even_months": 3.8,
        "risk_level": "Low-Medium",
        "required_skills": ["Substrate Preparation", "Humidity Control", "Harvesting"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "Growing demand in local restaurants, hotels, and vegetable markets; high profit margin on dry/fresh mushrooms.",
        "description": "Low-space indoor mushroom farming using wheat/paddy straw beds, temperature control, and dark room incubation."
    },
    {
        "id": "beekeeping",
        "name": "Honey Bee Farming & Packing",
        "category": "Agriculture & Livestock",
        "minimum_investment": 40000.0,
        "recommended_investment": 75000.0,
        "equipment_cost": 25000.0,
        "working_capital": 15000.0,
        "estimated_monthly_revenue": 25000.0,
        "estimated_monthly_expenses": 8000.0,
        "expected_profit": 17000.0,
        "break_even_months": 4.4,
        "risk_level": "Low",
        "required_skills": ["Bee Management", "Honey Extraction", "Flora Knowledge"],
        "location_suitability": ["Rural"],
        "demand_assumptions": "High demand for pure organic raw honey; additional income from beeswax and crop pollination boosting farm yields.",
        "description": "Setting up 20-50 bee boxes near flowering crop fields or orchards for seasonal honey harvesting and local packaging."
    },
    {
        "id": "organic-farming",
        "name": "Organic Vegetable & Medicinal Herb Farm",
        "category": "Agriculture & Livestock",
        "minimum_investment": 50000.0,
        "recommended_investment": 100000.0,
        "equipment_cost": 30000.0,
        "working_capital": 20000.0,
        "estimated_monthly_revenue": 32000.0,
        "estimated_monthly_expenses": 14000.0,
        "expected_profit": 18000.0,
        "break_even_months": 5.5,
        "risk_level": "Medium",
        "required_skills": ["Farming", "Composting", "Organic Certification Knowledge"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "Premium pricing in urban markets and direct-to-consumer farm subscriptions for pesticide-free produce.",
        "description": "Zero-chemical vegetable cultivation using vermicomposting, drip irrigation, and natural pest management."
    },
    {
        "id": "food-processing",
        "name": "Spices, Pickle & Flour Processing Unit",
        "category": "Agro-Processing",
        "minimum_investment": 60000.0,
        "recommended_investment": 110000.0,
        "equipment_cost": 45000.0,
        "working_capital": 25000.0,
        "estimated_monthly_revenue": 36000.0,
        "estimated_monthly_expenses": 19000.0,
        "expected_profit": 17000.0,
        "break_even_months": 6.5,
        "risk_level": "Low-Medium",
        "required_skills": ["Food Hygiene", "Grinding Machine Operation", "Packaging"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "Consistent daily consumption items in village households and kirana stores.",
        "description": "Micro-processing center equipped with pulverizers and sealing machines to produce packaged turmeric, chilli powder, wheat flour, and homemade pickles."
    },
    {
        "id": "tailoring",
        "name": "Boutique & Readymade Garment Tailoring",
        "category": "Textiles & Crafts",
        "minimum_investment": 25000.0,
        "recommended_investment": 50000.0,
        "equipment_cost": 20000.0,
        "working_capital": 10000.0,
        "estimated_monthly_revenue": 22000.0,
        "estimated_monthly_expenses": 8000.0,
        "expected_profit": 14000.0,
        "break_even_months": 3.5,
        "risk_level": "Low",
        "required_skills": ["Stitching", "Embroidery", "Pattern Design"],
        "location_suitability": ["Rural", "Semi-Urban", "Urban"],
        "demand_assumptions": "Steady demand for custom festive wear, school uniforms, and alteration services.",
        "description": "Small sewing shop equipped with motorized sewing machines, overlock machines, and cloth cutting tools."
    },
    {
        "id": "handicrafts",
        "name": "Bamboo, Clay & Jute Handicrafts Unit",
        "category": "Textiles & Crafts",
        "minimum_investment": 20000.0,
        "recommended_investment": 45000.0,
        "equipment_cost": 12000.0,
        "working_capital": 10000.0,
        "estimated_monthly_revenue": 20000.0,
        "estimated_monthly_expenses": 7000.0,
        "expected_profit": 13000.0,
        "break_even_months": 3.4,
        "risk_level": "Low",
        "required_skills": ["Artisan Crafting", "Manual Finishing", "Basic E-commerce"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "High eco-friendly product demand in city exhibitions, export aggregators, and online marketplaces.",
        "description": "Manufacturing artisanal home decor, utility baskets, eco-friendly bags, and terracotta pottery using locally available raw materials."
    },
    {
        "id": "small-retail",
        "name": "Rural General Provision Store (Kirana)",
        "category": "Retail & Trading",
        "minimum_investment": 75000.0,
        "recommended_investment": 140000.0,
        "equipment_cost": 30000.0,
        "working_capital": 50000.0,
        "estimated_monthly_revenue": 65000.0,
        "estimated_monthly_expenses": 48000.0,
        "expected_profit": 17000.0,
        "break_even_months": 8.2,
        "risk_level": "Low-Medium",
        "required_skills": ["Inventory Management", "Customer Service", "Basic Accounting"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "Essential household supply needs in high-footfall village junctions.",
        "description": "Neighborhood grocery store stocking FMCG products, grain staples, personal care items, and digital bill payment facility."
    },
    {
        "id": "mobile-repair",
        "name": "Smartphone Repair & Digital Service Center",
        "category": "Services & Repairs",
        "minimum_investment": 30000.0,
        "recommended_investment": 60000.0,
        "equipment_cost": 25000.0,
        "working_capital": 10000.0,
        "estimated_monthly_revenue": 26000.0,
        "estimated_monthly_expenses": 9000.0,
        "expected_profit": 17000.0,
        "break_even_months": 3.5,
        "risk_level": "Low",
        "required_skills": ["Electronics Repair", "Soldering", "Software Flashing"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "Rapid growth of smartphone penetration in rural areas creating continuous demand for display/battery replacement.",
        "description": "Compact workshop providing mobile phone repair, accessories sales, screen replacement, and recharge/money transfer services."
    },
    {
        "id": "solar-services",
        "name": "Solar Pump & Rooftop Maintenance Agency",
        "category": "Renewable Energy & Services",
        "minimum_investment": 90000.0,
        "recommended_investment": 160000.0,
        "equipment_cost": 50000.0,
        "working_capital": 40000.0,
        "estimated_monthly_revenue": 45000.0,
        "estimated_monthly_expenses": 22000.0,
        "expected_profit": 23000.0,
        "break_even_months": 7.0,
        "risk_level": "Medium",
        "required_skills": ["Electrical Maintenance", "Solar Panel Installation", "Sales"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "Government subsidies under PM-KUSUM promoting solar agriculture pumps and solar home lighting in off-grid villages.",
        "description": "Sales, installation, cleaning, and maintenance service agency for rural solar water pumps, home lighting systems, and solar streetlights."
    },
    {
        "id": "digital-services",
        "name": "Common Service Center (CSC) & Digital Kiosk",
        "category": "Services & IT",
        "minimum_investment": 40000.0,
        "recommended_investment": 70000.0,
        "equipment_cost": 35000.0,
        "working_capital": 15000.0,
        "estimated_monthly_revenue": 28000.0,
        "estimated_monthly_expenses": 10000.0,
        "expected_profit": 18000.0,
        "break_even_months": 3.9,
        "risk_level": "Low",
        "required_skills": ["Computer Operation", "Government Scheme Portal Knowledge", "Customer Service"],
        "location_suitability": ["Rural", "Semi-Urban"],
        "demand_assumptions": "Rural citizens requiring assistance for Aadhaar/PAN applications, PM-Kisan registration, insurance, printing, and banking services.",
        "description": "E-governance kiosk equipped with computer, biometric scanner, multi-function printer, and high-speed internet."
    },
    {
        "id": "goat-farming",
        "name": "Goat Rearing & Breeding Unit",
        "category": "Agriculture & Livestock",
        "minimum_investment": 60000.0,
        "recommended_investment": 110000.0,
        "equipment_cost": 30000.0,
        "working_capital": 25000.0,
        "estimated_monthly_revenue": 34000.0,
        "estimated_monthly_expenses": 14000.0,
        "expected_profit": 20000.0,
        "break_even_months": 5.5,
        "risk_level": "Medium",
        "required_skills": ["Livestock Care", "Fodder Growing", "Market Trading"],
        "location_suitability": ["Rural"],
        "demand_assumptions": "High festive and year-round demand for mutton with low initial infrastructure requirements and high multiplication rate.",
        "description": "Stall-fed or semi-intensive goat farming (10 females + 1 male starter unit) for meat production and breeding stock."
    },
    {
        "id": "fish-farming",
        "name": "Pond Aquaculture & Inland Fish Farming",
        "category": "Agriculture & Livestock",
        "minimum_investment": 100000.0,
        "recommended_investment": 180000.0,
        "equipment_cost": 55000.0,
        "working_capital": 45000.0,
        "estimated_monthly_revenue": 52000.0,
        "estimated_monthly_expenses": 24000.0,
        "expected_profit": 28000.0,
        "break_even_months": 6.4,
        "risk_level": "Medium-High",
        "required_skills": ["Water Quality Testing", "Fish Seed Stocking", "Feed Management"],
        "location_suitability": ["Rural"],
        "demand_assumptions": "High local consumer demand for fresh carp, Rohu, and Catla fish in rural markets.",
        "description": "Utilizing small natural ponds or excavated tanks for commercial freshwater fish culture using balanced floating feed."
    }
]

def get_all_businesses() -> List[Dict[str, Any]]:
    return RURAL_BUSINESSES

def get_business_by_id(b_id: str) -> Dict[str, Any]:
    for b in RURAL_BUSINESSES:
        if b["id"] == b_id:
            return b
    return RURAL_BUSINESSES[0] # Default fallback
